pythonic/courses/routes.py
# Importing Blueprint to organize routes, and request to access query parameters in the URL.
from flask import Blueprint, request

from pythonic.models import Lesson, Course
from flask import (
    render_template,
)

# Creating a Blueprint named 'courses' to group the related routes. 
# This helps in structuring the application and making it modular.
courses_bp = Blueprint("courses", __name__)


@courses_bp.route("/<string:course_title>")
def course(course_title):
    # Query the Course model to find a course by its title.
    course = Course.query.filter_by(title=course_title).first()

     # If a course is found, store its ID; otherwise, set course_id to None.
    course_id = course.id if course else None
    course = Course.query.get_or_404(course_id)

    # Get the page number from the URL query parameters. Defaults to page 1 if not specified.
    page = request.args.get("page", 1, type=int)
    lessons = Lesson.query.filter_by(course_id=course_id).paginate(
        page=page, per_page=6
    )
    return render_template(
        "course.html",
        title=course.title,
        course=course,
        lessons=lessons,
    )


@courses_bp.route("/courses")
def courses():
    """courses main route"""

     # Get the page number from the URL query parameters. Defaults to page 1 if not specified.
    page = request.args.get("page", 1, type=int)

    # Query the Course model to paginate and display 6 courses per page.
    courses = Course.query.paginate(page=page, per_page=6)
    return render_template("courses.html", title="Courses", courses=courses)

pythonic/lessons/routes.py
from flask import Blueprint
from pythonic.models import Lesson, Course
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    session,
    abort,
)
from pythonic.lessons.forms import (
    NewLessonForm,
    LessonUpdateForm,
)
from pythonic.courses.forms import NewCourseForm

from pythonic import db
from flask_modals import render_template_modal
from flask_login import (
    login_required,
    current_user,
)
from pythonic.helpers import save_picture
from pythonic.lessons.helpers import get_previous_next_lesson, delete_picture

lessons = Blueprint("lessons", __name__)


@lessons.route("/dashboard/new_lesson", methods=["GET", "POST"])
@login_required
def new_lesson():
    """Handles creation of new lessons and courses"""

    new_lesson_form = NewLessonForm()  # Form for creating a new lesson
    new_course_form = NewCourseForm()  # Form for creating a new course
    form = ""
    flag = session.pop("flag", False)

    # Determine which form is submitted
    if "content" in request.form:
        form = "new_lesson_form"
    elif "description" in request.form:
        form = "new_course_form"

    # Handle lesson creation
    if form == "new_lesson_form" and new_lesson_form.validate_on_submit():
        if new_lesson_form.thumbnail.data:
            picture_file = save_picture(
                new_lesson_form.thumbnail.data, "static/lesson_thumbnails"
            )
        lesson_slug = str(new_lesson_form.slug.data).replace(" ", "-")
        course = new_lesson_form.course.data
        lesson = Lesson(
            title=new_lesson_form.title.data,
            content=new_lesson_form.content.data,
            slug=lesson_slug,
            author=current_user,
            course_name=course,
            thumbnail=picture_file,
        )
        db.session.add(lesson)
        db.session.commit()
        flash("Your lesson has been created!", "success")
        return redirect(url_for("lessons.new_lesson"))

    # Handle course creation
    elif form == "new_course_form" and new_course_form.validate_on_submit():
        if new_course_form.icon.data:
            picture_file = save_picture(
                new_course_form.icon.data, "static/course_icons", output_size=(150, 150)
            )
        course_title = str(new_course_form.title.data).replace(" ", "-")
        course = Course(
            title=new_course_form.title.data,
            description=new_course_form.description.data,
            icon=picture_file,
        )
        db.session.add(course)
        db.session.commit()
        session["flag"] = True
        flash("New Course has been created!", "success")
        return redirect(url_for("users.dashboard"))

    # Render the appropriate form/modal
    user_permission = current_user.permission  # 'student' or 'mentor'
    admin_permission = current_user.is_authenticated and current_user.id == 1
    modal = None if flag else "newCourse"

    return render_template_modal(
        "new_lesson.html",
        title="New Lesson",
        new_lesson_form=new_lesson_form,
        new_course_form=new_course_form,
        active_tab="new_lesson",
        modal=modal,
        user_permission=user_permission,
        admin_permission=admin_permission,
    )


@lessons.route("/<string:course>/<string:lesson_slug>")
def lesson(lesson_slug, course):
    """Displays a lesson based on its slug and course"""

    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id)
    return render_template(
        "lesson_view.html",
        title=lesson.title,
        lesson=lesson,
        previous_lesson=previous_lesson,
        next_lesson=next_lesson,
    )


@lessons.route("/dashboard/user_lessons", methods=["GET", "POST"])
@login_required
def user_lessons():
    """Displays lessons created by the current user"""

    user_permission = current_user.permission  # 'student' or 'mentor'
    admin_permission = current_user.is_authenticated and current_user.id == 1

    return render_template(
        "user_lessons.html", title="Your Lessons",
        active_tab="user_lessons",
        user_permission=user_permission,
        admin_permission=admin_permission,

    )


@lessons.route("/<string:course>/<string:lesson_slug>/update", methods=["GET", "POST"])
def update_lesson(lesson_slug, course):
    """Handles lesson updates by the author"""

    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403) # Only the author can update the lesson
    form = LessonUpdateForm()
    if form.validate_on_submit():
        lesson.course_name = form.course.data
        lesson.title = form.title.data
        lesson.slug = str(form.slug.data).replace(" ", "-")
        lesson.content = form.content.data
        if form.thumbnail.data:
            delete_picture(lesson.thumbnail, "static/lesson_thumbnails")
            new_picture = save_picture(form.thumbnail.data, "static/lesson_thumbnails")
            lesson.thumbnail = new_picture
        db.session.commit()
        flash("Your lesson has been updated!", "success")
        return redirect(
            url_for("lessons.lesson", lesson_slug=lesson.slug, course=lesson.course_name.title)
        )
    elif request.method == "GET":
        form.course.data = lesson.course_name.title
        form.title.data = lesson.title
        form.slug.data = lesson.slug
        form.content.data = lesson.content
    return render_template(
        "update_lesson.html",
        title="Update | " + lesson.title,
        lesson=lesson,
        previous_lesson=previous_lesson,
        next_lesson=next_lesson,
        form=form,
    )


@lessons.route("/lesson/<lesson_id>/delete", methods=["POST"])
def delete_lesson(lesson_id):
    """Deletes a lesson by its author"""

    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)
    db.session.delete(lesson)
    db.session.commit()
    flash("Your lesson has been deleted!", "success")
    return redirect(url_for("lessons.user_lessons"))

pythonic/main/routes.py
from flask import Blueprint
import secrets
import os
from pythonic.models import Lesson, Course
from flask_ckeditor import upload_success, upload_fail
from flask_login import current_user
from flask import (
    render_template,
    url_for,
    request,
    send_from_directory,
)
from flask import current_app


main = Blueprint("main", __name__)


@main.route("/files/<path:filename>")
def uploaded_files(filename):
    path = os.path.join(current_app.root_path, "static/media")
    return send_from_directory(path, filename)


@main.route("/upload", methods=["POST"])
def upload():
    f = request.files.get("upload")
    extension = f.filename.split(".")[-1].lower()
    if extension not in ["jpg", "gif", "png", "jpeg"]:
        return upload_fail(message="File extension not allowed!")
    random_hex = secrets.token_hex(8)
    image_name = random_hex + extension
    f.save(os.path.join(current_app.root_path, "static/media", image_name))
    url = url_for("main.uploaded_files", filename=image_name)
    return upload_success(url, filename=image_name)


@main.route("/")
@main.route("/home")
def home():

    current_name = None
    # Initialize admin_permission as False by default
    admin_permission = False

    # Check if the user is authenticated first
    if current_user.is_authenticated:

        current_name = current_user.fname # show user first name

        if current_user.id == 1:
            # Render the admin page if the user is admin (id == 1)
            return render_template("admin.html", title='Admin Page')
        elif current_user.id > 1:
            # Set admin_permission to True for non-admin authenticated users
            admin_permission = True

    # Fetch lessons and courses for non-admin users or unauthenticated users
    lessons = Lesson.query.order_by(Lesson.date_posted.desc()).paginate(page=1, per_page=6)
    courses = Course.query.paginate(page=1, per_page=6)

    return render_template("home.html", 
                           lessons=lessons, 
                           courses=courses, 
                           admin_permission=admin_permission,
                           current_name=current_name)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

pythonic/users/routes.py
from flask import Blueprint
from pythonic.models import User, Lesson
from flask import (
    render_template,
    url_for,
    flash,
    redirect, # To redirect to different route
    request, # To access request data
)
from pythonic.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateProfileForm, #  Form to update profile information
    RequestResetForm, # Form to request a password reset
    ResetPasswordForm, # Form to reset the password

)
from pythonic import bcrypt, db  # For password hashing and database access
from flask_login import (
    login_required, # For protecting routes that require login
    login_user,
    current_user, # To access the currently logged-in user
    logout_user,
)
from pythonic.helpers import save_picture  # Helper function to save profile pictures
from pythonic.users.helpers import send_reset_email  # Helper function to send password reset emails

users = Blueprint("users", __name__)


"""Route for user registration"""
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated: # Redirect if already logged in
        return redirect(url_for("main.home"))
    form = RegistrationForm() # Create an instance of the registration form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        # Create a new user
        user = User(
            fname=form.fname.data,
            lname=form.lname.data,
            username=form.username.data,
            permission=form.permission.data,
            email=form.email.data,
            password=hashed_password,
        )
        db.session.add(user) # Add the user to the database
        db.session.commit()
        flash(f"Account created successfully for {form.username.data}", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


"""Route for user login"""
@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()  # Create an instance of the login form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()  # Find the user by email
        if user and bcrypt.check_password_hash(user.password, form.password.data): # Check the password
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash("You have been logged in!", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check credentials", "danger")
    return render_template("login.html", title="Login", form=form)


"""Route to log out the user"""
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


"""Route to access the dashboard (requires login)"""
@users.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    # Get the user permission from the current logged-in user
    user_permission = current_user.permission  # 'student' or 'mentor'
    admin_permission = current_user.is_authenticated and current_user.id == 1

    if user_permission == 'student':
        return redirect(url_for("users.profile"))

    # Render the appropriate template and pass the user_permission
    return render_template('dashboard.html',
                            title="Dashboard",
                            user_permission=user_permission,
                            admin_permission=admin_permission,
                            active_tab=None)


"""Route for user profile"""
@users.route("/dashboard/profile", methods=["GET", "POST"])
@login_required
def profile():
    profile_form = UpdateProfileForm() # Create an instance of the profile update form
    if profile_form.validate_on_submit():
        if profile_form.picture.data:
            picture_file = save_picture(
                profile_form.picture.data, "static/user_pics", output_size=(150, 150)  
            )
            current_user.image_file = picture_file
 
        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data
        current_user.bio = profile_form.bio.data
        db.session.commit()  # save the changes to the database
        flash("Your profile has been updated", "success")
        return redirect(url_for("users.profile"))

    elif request.method == "GET":

        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.bio.data = current_user.bio

    # Get the path to the user's image
    image_file = url_for("static", filename=f"user_pics/{current_user.image_file}")
    user_permission = current_user.permission  # 'student' or 'mentor'
    admin_permission = current_user.is_authenticated and current_user.id == 1


    return render_template(
        "profile.html",
        title="Profile",
        profile_form=profile_form,
        image_file=image_file,
        active_tab="profile",
        user_permission=user_permission,
        admin_permission=admin_permission,
    )


"""Route to view lessons by a specific author (username)"""
@users.route("/author/<string:username>", methods=["GET"])
def author(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get("page", 1, type=int)
    lessons = (
        Lesson.query.filter_by(author=user)
        .order_by(Lesson.date_posted.desc())
        .paginate(page=page, per_page=6)
    )
    return render_template("author.html", lessons=lessons, user=user)


"""Route to request a password reset"""
@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()  # Create an instance of the password reset request form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash(
            "If this account exists, you will receive an email with instructions",
            "info",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


"""Route to reset the password using a token"""
@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if not user:
        flash("The token is invalid or expired", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password  # Update the user's password
        db.session.commit()
        flash(f"Your password has been updated. You can now log in", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_password.html", title="Reset Password", form=form)

pythonic/templates/admin.html
{% extends "dashboard.html"%}
{% block profile %}

    <h1>hello, {{ current_user.fname }} </h1>
    <h3>You login as an Admin</h3>
    <br>
    <br>
    <a href="/admin/user/" class="btn btn-primary ms-2">Go to Admin Page</a>

    <a href="/courses" class="btn btn-primary ms-2">Show all courses</a>


{% endblock %}

pythonic/templates/course.html
{% extends "layout.html"%}
{% block content %}
<div class="container-fluid bg-secondary">
    <div class="container">
        <div class="row p-5">
            <div class="col-6">
                <img src="{{url_for('static', filename='course_icons/'+course.icon)}}" alt="">
            </div>
            <div class="col-6">
                <span class="lead text-light">{{course.description}}</span>
            </div>
        </div>
    </div>
</div>
<section class="bg-light">
    <div class="container p-5">
        <div class="row mb-5 ">
        </div>
        <div class="row">
            {% for lesson in lessons.items %}
            <div class="col-sm-12 col-md-6 col-lg-4 pb-5 d-flex align-items-stretch">
                <div class="card lesson">
                    <img src="{{url_for('static', filename='lesson_thumbnails/'+lesson.thumbnail)}}" class="card-img">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">
                            <a class="text-decoration-none text-dark"
                                href="{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}">{{lesson.title}}</a>
                        </h5>
                        <span><img class="article-img rounded-circle"
                                src="{{url_for('static', filename='user_pics/'+lesson.author.image_file)}}" alt="">By:
                            <a href="{{url_for('users.author', username=lesson.author.username)}}"
                                class="link">{{lesson.author.username}}</a></span>
                        <span class="text-muted">On: {{lesson.date_posted.strftime('%Y-%m-%d')}}</span>

                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- pagination links -->
            <nav class="mt-5" aria-label="...">
                <ul class="pagination" style="display: flex; justify-content: flex-end">
                    {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                    {% if lessons.page == page_num %}
                    <li class="page-item active">
                        <a href="{{url_for('courses.course', course_title=course.title, page=page_num)}}"
                            class="page-link">{{page_num}}</a>
                    </li>
                    {%else%}
                    <li class="page-item">
                        <a href="{{url_for('courses.course', course_title=course.title, page=page_num)}}"
                            class="page-link">{{page_num}}</a>
                    </li>
                    {%endif%}
                    {% else %}
                    <span class="mx-2">...</span>
                    {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
</section>

{% endblock content%}

pythonic/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
        <!-- Favicon links -->
        <link rel="apple-touch-icon" sizes="144x144" href="/static/Logo.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/static/Logo.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/Logo.png">
        <link rel="manifest" href="/static/site.webmanifest">
        <link rel="mask-icon" href="/static/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% if title %}
    <title>Future-Courses - {{title}}</title>
    {% else %}
    <title>Future Courses</title>
    {%endif%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <link rel="icon" href="{{ url_for('static', filename='Logo3.png') }}" type="image/x-icon">

    {{ modals() }}
    {{ ckeditor.load_code_theme() }}
</head>

<body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark py-1 fixed-top" style="background-color: #182538;">
        <div class="container">
            <a href="{{url_for('main.home')}}" class="navbar-brand">
                <img src="{{ url_for('static', filename='Logo2.png') }}" alt="Logo" style="height: 60px; width: 70px; margin-right: 10px">
                <b>Future Courses</b>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{url_for('main.about')}}" class="nav-link"><b>About</b></a>
                    </li>
                        {% if admin_permission %}
                            <li class="nav-item">
                                {% if request.path=='/home'%}
                                <a href="#learn" class="nav-link"><b>Start Learning</b></a>
                                {% else %}
                                <a href="{{url_for('courses.courses')}}" class="nav-link"><b>Start Learning</b></a>
                                {% endif %}
                            </li>
                        {% endif %}
                    </ul>
                <!-- User Links -->
                <ul class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                    <div class="dropdown show">
                        <button class="btn btn-dark dropdown-toggle" style="background-color: #142135;" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                           My Account  
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li class="nav-item">
                                <a href="{{ url_for('users.dashboard') }}" class="dropdown-item"><b>Dashboard</b></a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url_for('users.logout') }}" class="dropdown-item"><b>Logout</b></a>
                            </li>
                        </ul>
                    </div>


                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('users.register') }}" class="nav-link"><b>Register</b></a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('users.login') }}" class="nav-link"><b>Login</b></a>
                    </li>
                    {% endif%}
                </ul>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center">
        {{message}}
    </div>
    {% endfor %}

    {% endif %}
    {% endwith %}
    {% block content%} {% endblock %}
    <!-- footer -->

    <footer class="mt-auto" style="background-color: #182538;">
        <div class="container p-2">
            <div class="row text-center text-white">
                <div class="col-md-12 col-lg-4 pb-2">
                    <h4 class="text-center text-decoration-underline">Quick Links</h4>
                    <ul class=" nobull pt-3">
                        <li><a href="#" class="link text-white">Privacy Policy</a></li>
                        <li><a href="#" class="link text-white">Terms & Conditions</a></li>
                    </ul>
                </div>
                <div class="col-md-12 col-lg-4">
                    <h4 class="text-center text-decoration-underline pb-3">Social Links</h4>
                    <a href="https://github.com/Medo20300" class="text-white p-2" target="_blank"><i class="bi-github"></i></a>
                    <a href="https://www.youtube.com/@ALXAfrica" class="text-white p-2" target="_blank"><i class="bi-youtube"></i></a>
                    <a href="https://www.facebook.com/alxafrica" class="text-white p-2" target="_blank"><i class="bi-facebook"></i></a>
                    <a href="https://x.com/alx_africa?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" class="text-white p-2" target="_blank"><i class="bi-twitter"></i></a>
                    <a href="https://www.instagram.com/alx_africa/?hl=ar" class="text-white p-2" target="_blank"><i class="bi-instagram"></i></a>
                    <a href="https://www.tiktok.com/@alx_africa" class="text-white p-2" target="_blank"><i class="bi-tiktok"></i></a>

                </div>
                <div class="col-md-12 col-lg-4 pb-2">
                    <h4 class="text-center text-decoration-underline pb-3">Contact Us</h4>
                    <p class="lead"><b>FutureCourses.project@gmail.com</b></p>
                    <p class="lead"><b>WatsApp</b>01014253299</p>
                </div>
            </div>
            <!-- <footer class="bg-dark text-white mt-auto">
                <div class="container text-center py-4">
                    <h4 class="text-decoration-underline">Subscribe to our Newsletter</h4>
                    <form action="/subscribe" method="POST" class="d-flex justify-content-center pt-2">
                        <input type="email" name="email" placeholder="Enter your email" class="form-control w-50" required>
                        <button type="submit" class="btn btn-primary ms-2">Subscribe</button>
                    </form>
                </div>
            </footer> -->
        
            <div class="col text-white text-center position-relative">
                <p class="lead font-weight-bold">Copyright &copy; 2024 | Future-Courses</p>
                <a href="#" class="position-absolute bottom-0 end-0">
                    <i class="bi bi-arrow-up-circle h1" style="color: #535FD7;"></i>
                </a>
            </div>
        </div>

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

pythonic/templates/lesson_view.html
{% extends "lesson.html" %}
{% block lesson %}
<div class="container pt-5">
    <br>
    <h2>{{lesson.title}}</h2>
    <hr>
    {{lesson.content | safe}}
</div>

{% endblock lesson %}

pythonic/templates/login.html
{%extends "layout.html"%}
{% block content%}
<div class="container my-5 border">
    <form action="" method="POST">
        {{ form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Log In</legend>

            <div class="form-group">
                {{ form.email.label(class='form-control-label')}}
                {% if form.email.errors%}
                {{ form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.password.label(class='form-control-label')}}
                {% if form.password.errors%}
                {{ form.password(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class='form-control form-control-lg')}}
                {% endif %}

            </div>
            <div class="form-group my-3">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
            <div class="form-check">
                {{form.remember(class='form-check-input')}}
                {{form.remember.label(class='form-check-input-label')}}
            </div>
        </fieldset>
    </form>
    <small class="text-muted ml-2">
        <a class="link" href="{{ url_for('users.reset_request') }}">Forgeot Password?
        </a>
    </small>
    <small class="text-muted">
        Need An Account?
        <a class="ml-2" href="{{url_for('users.register')}}"> Sign Up Here</a>
    </small>
</div>
{% endblock content %}